# Path to project config (if it exists, this is loaded instead of config.yaml)
# controled_app_config_file: '../../u107_level_driven_algo/configs/config-control-panel.yaml'
controled_app_config_file: '../../u110_long_traget_algo/configs/config-control-panel.yaml'