control_panel:
  projectName: Control Panel G

  # Server ports
  ports:
    vite: 7106  # Vite development server port
    control_panel_api_port: 5109 # Control Panel API server port

  api:
    host: "0.0.0.0"
    controlPanelUrl: http://127.0.0.1:5109